chore: Add mCAKE sdCAKE in stableswap
pancakeswap/pancake-subgraph pull request #249
Opened 2024-01-08 05:17 UTC by chef-huan

2024-01-08 05:24 UTC, chefjackson approved these changes, later dismissed

2024-01-09 02:44 UTC, chefjackson commented on subgraphs/exchange-stableswap/subgraph.yaml
> +          file: ./abis/PairV3.json
Need to add to the liquidity event handlers as well

2024-01-09 03:52 UTC, chefjackson approved these changes

2024-01-09 04:23 UTC, chefjackson commented on subgraphs/exchange-stableswap/mappings/utils/index.ts
> +export let CAKE_ADDRESS = "0x0E09FaBB73Bd3Ade0a17ECC321fD13a19e81cE82";
should use lowercase

2024-01-09 04:23 UTC, chefjackson requested changes
cake address should use lowercase

2024-01-10 00:15 UTC, chefjackson approved these changes

2024-01-10 04:29 UTC, merged

2024-02-01 09:16 UTC, goashnik reviewed
✌️